[package]
name = "mosaic_generator"
version = "0.1.0"
edition = "2021"
authors = ["Przemyslaw Kaminski <przemyslaw.m.kaminski@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.8", features = ["derive"] }
image = "0.24.1"
rayon = "1.5.2"

